server:
  port: 8080

spring:
  application:
    name: "accounts"
  profiles:
    active: "prod" #by default prod is active profile
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

  config:
    import: "optional:configserver:http://localhost:8071/" #optional means configs are optional
  #rabbitmq:
  #  host: "localhost"
  #  port: 5672
  #  username: "guest"
  #  password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*" #expose all management endpoints
  endpoint:
    shutdown:
      enabled: true # deregister instance from eureka on shutdown
  info:
    env:
      enabled: true # enables info endpoint for Eureka dashboard

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true # will register with ip address instead of DNS
  client:
    fetchRegistry: true # indicates client should fetch eureka registry from eureka server
    registerWithEureka: true # indicates if client should registry its information with eureka server to be discoverable by others
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"