# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loans-deployment
serviceName: loans
appLabel: loans
appName: loans

replicaCount: 1

image:
  repository: spartanghost17/loans
  tag: s14

containerPort: 8090

service:
  type: ClusterIP
  ports:
    - name: loans
      port: 8090
      targetPort: 8090

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
rabbit_enabled: true
datasource_enabled: true
app_type: ms
databaseName: loansdb
env_var_enabled: true