# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: cardsdb-deployment
serviceName: cardsdb
appLabel: cardsdb
appName: cardsdb

replicaCount: 1

image:
  repository: mysql
  tag: latest

containerPort: 3306

service:
  type: ClusterIP
  port: 3306
  targetPort: 3306

appname_enabled: false
profile_enabled: false
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false
rabbit_enabled: false
datasource_enabled: true
app_type: db
databaseName: cardsdb