server:
  port: 8080

spring:
  application:
    name: "accounts"
  profiles:
    active: "prod" #by default prod is active profile
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

  config:
    import: "optional:configserver:http://localhost:8071/" #optional means configs are optional
  #rabbitmq:
  #  host: "localhost"
  #  port: 5672
  #  username: "guest"
  #  password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*" #expose all management endpoints
