---
# Deployment and Service for accountsdb
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountsdb
  labels:
    apps: accountsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountsdb
  template:
    metadata:
      labels:
        app: accountsdb
    spec:
      containers:
        - name: accountsdb
          image: mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: ACCOUNTSDB_NAME
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eazybank-secrets
                  key: ACCOUNTSDB_PASSWORD
          ports:
            - containerPort: 3306
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1"]
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: accountsdb
  labels:
    apps: accountsdb
spec:
  selector:
    app: accountsdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
# Deployment and Service for loansdb
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loansdb
  labels:
    apps: loansdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loansdb
  template:
    metadata:
      labels:
        app: loansdb
    spec:
      containers:
        - name: loansdb
          image: mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: LOANSDB_NAME
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eazybank-secrets
                  key: LOANSDB_PASSWORD
          ports:
            - containerPort: 3306
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1"]
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: loansdb
  labels:
    apps: loansdb
spec:
  selector:
    app: loansdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
# Deployment and Service for cardsdb
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardsdb
  labels:
    apps: cardsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardsdb
  template:
    metadata:
      labels:
        app: cardsdb
    spec:
      containers:
        - name: cardsdb
          image: mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: CARDSDB_NAME
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eazybank-secrets
                  key: CARDSDB_PASSWORD
          ports:
            - containerPort: 3306
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1"]
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cardsdb
  labels:
    apps: cardsdb
spec:
  selector:
    app: cardsdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
