apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    apps: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4.0-management-alpine
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: eazybank-secrets
                  key: RABBITMQ_DEFAULT_PASS
          ports:
            - containerPort: 5672 # Messaging port
            - containerPort: 15672 # Management UI port

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    apps: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: messaging
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management-ui
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: LoadBalancer
