# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

replicaCount: 1

image:
  repository: spartanghost17/accounts
  tag: s14

containerPort: 8080

service:
  type: ClusterIP
  ports:
    - name: accounts
      port: 8080
      targetPort: 8080

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: true
rabbit_enabled: true
datasource_enabled: true
app_type: ms
databaseName: accountsdb
env_var_enabled: true