deploymentName: rabbit-deployment
serviceName: rabbit
appLabel: rabbit
appName: rabbit

replicaCount: 1

image:
  repository: rabbitmq
  tag: 3.13-management-alpine

containerPort: 5672

service:
  type: ClusterIP
  ports:
    - name: rabbit
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672

# Health check settings
healthcheck:
  enabled: true
  interval: 10s
  timeout: 5s
  retries: 10
  start_period: 5s

appname_enabled: false
profile_enabled: false
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false
rabbit_enabled: false
rabbit_server: true
datasource_enabled: false
app_type: ms
env_var_enabled: true