server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod" #by default prod is active profile
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/" #optional means configs are optional
  #rabbitmq:
  #  host: "localhost"
  #  port: 5672
  #  username: "guest"
  #  password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*" #expose all management endpoints
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true # deregister instance from eureka on shutdown
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true # enables info endpoint for Eureka dashboard
  metrics: # expose metrics endpoint for prometheus or other metric collection
    tags:
      application: ${spring.application.name} # group metrics under application name

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true # will register with ip address instead of DNS
  client:
    fetchRegistry: true # indicates client should fetch eureka registry from eureka server
    registerWithEureka: true # indicates if client should registry its information with eureka server to be discoverable by others
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "cards"
    description: "Eazy Bank Cards Application"
    version: "1.0.0"

# enable logging
logging:
  level:
    com:
      eazybytes:
        cards: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"